const mechanicalInventions = [
    {
        id: 'IID0',
        date_invented: null,
        ancient: true,
        modern: false,
        invention_name: 'Manioc Squeezer',
        invention_type: 'Culinary',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: null,
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'South America',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.15'],
        primary_source_ids: null
    },
    {
        id: 'IID1',
        date_invented: null,
        ancient: true,
        modern: false,
        invention_name: 'Boomerang',
        invention_type: 'Weapons',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: null,
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'Australia',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.15'],
        primary_source_ids: null
    },
    {
        id: 'IID2',
        date_invented: null,
        ancient: true,
        modern: false,
        invention_name: "Toggle Joint Harpoon",
        invention_type: 'Weapons',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: null,
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: null,
        regions: null,
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.15'],
        primary_source_ids: null
    },
    {
        id: 'IID3',
        date_invented: -285,
        ancient: true,
        modern: false,
        invention_name: "Water Clock",
        invention_type: 'Timekeeping',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: 'Ktsebios (Ctesibius)',
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'Ancient Alexandria',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.138'],
        primary_source_ids: null
    },
    {
        id: 'IID4',
        date_invented: null,
        ancient: true,
        modern: false,
        invention_name: "Crossbow",
        invention_type: 'Weapons',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: null,
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: true,
        regions: 'Far East, Mediterranean',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.20'],
        primary_source_ids: null
    },
    {
        id: 'IID5',
        date_invented: -285,
        ancient: true,
        modern: false,
        invention_name: 'Force Pump',
        invention_type: 'Plumbing',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: 'Ktsebios (Ctesibius)',
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'Ancient Alexandria',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.137'],
        primary_source_ids: null
    },
    {
        id: 'IID6',
        date_invented: -285,
        ancient: true,
        modern: false,
        invention_name: 'Hydraulic Pipe Organ',
        invention_type: 'Musical Instruments',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: 'Ktsebios (Ctesibius)',
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'Ancient Alexandria',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.137'],
        primary_source_ids: null
    },
    {
        id: 'IID7',
        date_invented: -285,
        ancient: true,
        modern: false,
        invention_name: 'Musical Keyboard',
        invention_type: 'Musical Instruments',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: 'Ktsebios (Ctesibius)',
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'Ancient Alexandria',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.138'],
        primary_source_ids: null
    },
    {
        id: 'IID8',
        date_invented: -285,
        ancient: true,
        modern: false,
        invention_name: 'Metal Spring',
        invention_type: 'Mechanics',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: 'Ktsebios (Ctesibius)',
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'Ancient Alexandria',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.138'],
        primary_source_ids: null
    },
    {
        id: 'IID9',
        date_invented: -270,
        ancient: true,
        modern: false,
        invention_name: 'Singing Cornucopia',
        invention_type: 'Miscellaneous',
        dimensions: null,
        iteration: null,
        iteration_of: null,
        materials: null,
        inventor: 'Ktsebios (Ctesibius)',
        research_groups: null,
        model: null,
        model_image: null, 
        multi_regional: false,
        regions: 'Ancient Alexandria',
        number_of_corroborative_sources: 1,
        source_ids: ['C23A1'],
        source_page_references: ['p.137'],
        primary_source_ids: null
    },
]

export default MechanicalInventions;
