const sources = [
    {
        source_id: 'C23A1',
        source_reliability_rating: 76,
        source_title: 'Ancient Engineers',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: '1-9',
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'L Sprague De Camp',
        publisher: 'Barns & Noble Books',
        website_name: null,
        website_url: null,
        city_published: ['New York'],
        regions: 'The United States of America',
        original_language: 'English',
        isbn: '0-88029-456-6',
        year_published: 1993,
        original_year_published_bce: null,
        original_year_published_ad: 1993,
        source_type: 'E-Book',
        modern: true,
    },
    {
        source_id: 'C23A2',
        source_reliability_rating: null,
        source_title: 'Where are the Women in Engineering: A Century Old Story',
        number_of_references: null,
        journal: 'Institution of Engineering and Technology',
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Emily Reese, Graeme Gooday',
        publisher: 'Institution of Engineering and Technology',
        website_name: null,
        website_url: null,
        city_published: null,
        regions: null,
        original_language: 'English',
        isbn: null,
        year_published: 2019,
        original_year_published_bce: null,
        original_year_published_ad: 2019,
        source_type: 'Journal Article',
        modern: true,
    },
    {
        source_id: 'C23A3',
        source_reliability_rating: null,
        source_title: 'The Woman Engineer',
        number_of_references: null,
        journal: null,
        volume: 1,
        chapter: null,
        number: '1-2',
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Iris A. Cummins',
        publisher: 'The Women\'s Engineering Society',
        website_name: null,
        website_url: null,
        city_published: ['London'],
        regions: 'The United Kingdom',
        original_language: 'English',
        isbn: null,
        year_published: 1919,
        original_year_published_bce: null,
        original_year_published_ad: 1919,
        source_type: 'Journal Article',
        modern: true,
    },
    {
        source_id: 'C23A4',
        source_reliability_rating: null,
        source_title: 'Rise of the Rocket Girls: The Women Who Propelled Us, from the First Woman to the Moon to Mars',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Nathalia Holt',
        publisher: 'Little, Brown and Company',
        website_name: null,
        website_url: null,
        city_published: ['New York', 'Boston', 'London'],
        regions: null,
        original_language: 'English',
        isbn: '978-0-316-33891-2',
        year_published: 2016,
        original_year_published_bce: null,
        original_year_published_ad: 2016,
        source_type: 'E-Book',
        modern: true,
    },
    {
        source_id: 'C23A5',
        source_reliability_rating: null,
        source_title: 'The Evolution of the Spacesuit!',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'The Space Race (YouTube Channel)',
        publisher: 'The Space Race (YouTube Channel)',
        website_name: 'YouTube',
        website_url: 'https://www.youtube.com/',
        city_published: null,
        regions: null,
        original_language: 'English',
        isbn: null,
        year_published: 2023,
        original_year_published_bce: null,
        original_year_published_ad: 2023,
        source_type: 'Video',
        modern: true,
    },
    {
        source_id: 'C23A6',
        source_reliability_rating: null,
        source_title: 'History of Egypt',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Manetho',
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: null,
        regions: 'Ancient Egypt',
        original_language: 'Greek',
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Book',
        modern: false,
    },
    {
        source_id: 'C23A7',
        source_reliability_rating: null,
        source_title: 'The Old Kingdom in Egypt and the Beginning of the First Intermediate Period',
        number_of_references: null,
        journal: 'The Cambridge Ancient History',
        volume: 1,
        chapter: 14,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'W. Stevenson Smith',
        publisher: 'The Syndics of the Cambridge University Press',
        website_name: null,
        website_url: null,
        city_published: ['London', 'Ibadan'],
        regions: 'The United Kingdom',
        original_language: 'English',
        isbn: null,
        year_published: 1962,
        original_year_published_bce: null,
        original_year_published_ad: 1962,
        source_type: 'Journal Article',
        modern: true,
    },
    {
        source_id: 'C23A8',
        source_reliability_rating: null,
        source_title: 'Dynasties of Ancient Egypt: Pharoahs in Order',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: 'https://www.historyextra.com/period/ancient-egypt/timeline-ancient-egypt-dynasties-in-order/',
        archeological_site: null,
        witnesses: null,
        authors: 'Charlotte Hodgman',
        publisher: null,
        website_name: 'History Extra',
        website_url: 'https://www.historyextra.com/',
        city_published: null,
        regions: null,
        original_language: 'English',
        isbn: null,
        year_published: 2022,
        original_year_published_bce: null,
        original_year_published_ad: 2022,
        source_type: 'Website Article',
        modern: true,
    },
    {
        source_id: 'C23A9',
        source_reliability_rating: null,
        source_title: 'Early Dynastic Egypt',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Toby Wilkinson',
        publisher: 'Routledge',
        website_name: null,
        website_url: null,
        city_published: null,
        regions: null,
        original_language: null,
        isbn: null,
        year_published: 1999,
        original_year_published_bce: null,
        original_year_published_ad: 1999,
        source_type: 'Book',
        modern: true,
    },
    {
        source_id: 'C23A10',
        source_reliability_rating: null,
        source_title: 'The Book of Proofs',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: 1,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Richard Hammock',
        publisher: 'Richard Hammock',
        website_name: null,
        website_url: null,
        city_published: null,
        regions: null,
        original_language: null,
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Book',
        modern: true,
    },
    {
        source_id: 'C23A11',
        source_reliability_rating: null,
        source_title: 'Discrete Mathematics and Its Applications',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Kenneth H. Rosen',
        publisher: 'McGraw-Hill Education',
        website_name: null,
        website_url: null,
        city_published: null,
        regions: null,
        original_language: 'English',
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Book',
        modern: true,
    },
    {
        source_id: 'C23A12',
        source_reliability_rating: null,
        source_title: 'King Sennacherib: The Warrior King of the Neo-Assyrian Empire',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: 'https://www.thecollector.com/king-sennacherib-neo-assyrian-empire/',
        archeological_site: null,
        witnesses: null,
        authors: 'Greg Beyer',
        publisher: 'The Collector',
        website_name: 'The Collector',
        website_url: 'https://www.thecollector.com/',
        city_published: null,
        regions: null,
        original_language: 'English',
        isbn: null,
        year_published: 2023,
        original_year_published_bce: null,
        original_year_published_ad: 2023,
        source_type: 'Website Article',
        modern: true,
    },
    {
        source_id: 'P23A1',
        source_reliability_rating: 27,
        source_title: 'Inscription of Khnumabra',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: 'Khnumabra',
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: 'Memphis',
        regions: 'AncientEgypt',
        original_language: 'Hieroglyphic',
        isbn: null,
        year_published: null,
        original_year_published_bce: 490,
        original_year_published_ad: null,
        source_type: 'Inscription',
        modern: false,
    },
    {
        source_id: 'P23A2',
        source_reliability_rating: null,
        source_title: 'Firsthand Witness Testimony of Manetho',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: 'Manetho',
        authors: null,
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: null,
        regions: null,
        original_language: null,
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Eyewitness Testimony',
        modern: false,
    },
    {
        source_id: 'P23A3',
        source_reliability_rating: null,
        source_title: 'Firsthand Witness Testimony of Herodotos',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: 'Herodotos',
        authors: null,
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: null,
        regions: null,
        original_language: null,
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Eyewitness Testimony',
        modern: false,
    },
    {
        source_id: 'P23A4',
        source_reliability_rating: null,
        source_title: 'Stone Paintings in Khuit-Khufu (Great Pyramid of Giza)',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: 'Interior of Khuit-Khufu (Great Pyramid of Giza)',
        witnesses: null,
        authors: null,
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: null,
        regions: 'Ancient Egypt',
        original_language: 'Hieroglyphic',
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Inscription',
        modern: false,
    },
    {
        source_id: 'P23A5',
        source_reliability_rating: null,
        source_title: 'Ptolemaic Inscription on the Island of Sihei',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: null,
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: null,
        regions: 'Ancient Egypt',
        original_language: 'Hieroglyphic',
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Inscription',
        modern: false,
    },
    {
        source_id: 'P23A6',
        source_reliability_rating: null,
        source_title: 'Wall Scribblings of Eighteenth Dynasty visitors to the Step Pyramid',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: null,
        witnesses: null,
        authors: null,
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: null,
        regions: 'Ancient Egypt',
        original_language: 'Hieroglyphic',
        isbn: null,
        year_published: '1550-1295 BCE',
        original_year_published_bce: '1550-1295 BCE',
        original_year_published_ad: null,
        source_type: 'Inscription',
        modern: false,
    },
    {
        source_id: 'P23A7',
        source_reliability_rating: null,
        source_title: 'Inscription on Statue Base of King Djoser',
        number_of_references: null,
        journal: null,
        volume: null,
        chapter: null,
        number: null,
        website_article_url: null,
        archeological_site: 'Excavations of the Step Pyramid',
        witnesses: null,
        authors: null,
        publisher: null,
        website_name: null,
        website_url: null,
        city_published: null,
        regions: 'Ancient Egypt',
        original_language: 'Hieroglyphic',
        isbn: null,
        year_published: null,
        original_year_published_bce: null,
        original_year_published_ad: null,
        source_type: 'Inscription',
        modern: false,
    },
    
]

export default sources;
